// Section 1: Economic Factors and Business Information (20 questions, ~15%)
window.CARDS = window.CARDS || [];
[
// --- Business cycle & macro ---
['Business cycle','Four phases of the business cycle, in order?','Expansion → Peak → Contraction (recession) → Trough. Then recovery/expansion begins again.'],
['Business cycle','Definition of a recession?','Two consecutive quarters of declining GDP (real GDP falling). A depression is a severe, prolonged recession (roughly 6+ quarters).'],
['Business cycle','Leading economic indicators (name 5)?','Stock prices (S&P 500), building permits, new unemployment claims, manufacturers\' new orders, money supply (M2), average weekly hours, consumer expectations, yield curve spread.'],
['Business cycle','Coincident indicators?','Industrial production, personal income (less transfers), nonfarm payroll employment, manufacturing & trade sales. They move WITH the economy.'],
['Business cycle','Lagging indicators?','Average duration of unemployment, prime rate, CPI for services, ratio of consumer credit to income, commercial & industrial loans outstanding, labor cost per unit of output. They confirm trends AFTER the fact.'],
['Business cycle','Which industries are cyclical vs. defensive vs. counter-cyclical?','Cyclical: autos, steel, housing, capital goods, luxury. Defensive: food, utilities, pharma, tobacco, alcohol. Counter-cyclical: discount retailers, gold (do well in downturns).'],
['Business cycle','Growth vs. value vs. cyclical stock: how do they behave in the cycle?','Cyclicals do best early in expansion. Defensive/value hold up in contraction. Growth stocks are hurt most by rising rates (future earnings discounted more).'],
['Macro','GDP vs. GNP?','GDP = output produced INSIDE the country\'s borders regardless of who owns it. GNP = output produced by the country\'s nationals/companies anywhere in the world.'],
['Macro','Nominal GDP vs. real GDP?','Real GDP is adjusted for inflation (uses constant dollars). Nominal is in current dollars. Real GDP is the measure of true economic growth.'],
['Macro','What is the GDP deflator?','A price index used to convert nominal GDP to real GDP: Real GDP = Nominal GDP ÷ (deflator/100).'],
// --- Inflation & interest rates ---
['Inflation','CPI measures what? PPI?','CPI: price of a fixed basket of consumer goods & services (retail level). PPI: prices received by producers (wholesale level) — a leading indicator of CPI.'],
['Inflation','Inflation vs. deflation vs. disinflation vs. stagflation?','Inflation: rising prices. Deflation: falling prices. Disinflation: inflation slowing but still positive. Stagflation: high inflation + stagnant growth/high unemployment.'],
['Inflation','Who is hurt most by unexpected inflation?','Lenders/bondholders and people on fixed incomes. Borrowers benefit (repay with cheaper dollars). Bond prices fall as rates rise.'],
['Inflation','Which assets historically do best in inflation?','Real assets: real estate, commodities, gold, TIPS, equities of companies with pricing power. Worst: long-term fixed-rate bonds, cash.'],
['Interest rates','Real interest rate formula?','Real rate ≈ nominal rate − inflation rate. (Precisely: (1+nominal)/(1+inflation) − 1.)'],
['Interest rates','Discount rate vs. federal funds rate vs. prime rate?','Discount: Fed lends to banks. Fed funds: banks lend to each other overnight (Fed\'s target rate). Prime: banks lend to best corporate customers. Discount rate is the only one SET directly by the Fed; fed funds is targeted; prime is set by banks.'],
['Interest rates','Which short-term rate is most volatile?','The federal funds rate (changes daily with bank reserves).'],
['Interest rates','Rank from lowest to highest: discount rate, fed funds, prime, broker call rate','Typically: fed funds ≈ discount (lowest) < broker call < prime (highest).'],
// --- Monetary & fiscal policy ---
['Fed policy','Three tools of the Federal Reserve (monetary policy)?','1) Open market operations (buying/selling Treasuries via FOMC — most used), 2) Discount rate, 3) Reserve requirements (rarely changed). Also: interest on reserves, margin (Reg T).'],
['Fed policy','To fight inflation (tighten), the Fed will…?','SELL government securities (drains reserves), RAISE the discount rate, RAISE reserve requirements. Money supply shrinks, rates rise.'],
['Fed policy','To stimulate the economy (ease), the Fed will…?','BUY government securities (adds reserves), LOWER the discount rate, LOWER reserve requirements. Money supply grows, rates fall.'],
['Fed policy','Who conducts open market operations?','The FOMC (Federal Open Market Committee).'],
['Fiscal policy','Fiscal policy is controlled by whom, using what tools?','Congress and the President. Tools: taxation and government spending. (Keynesian theory: government spending drives demand.)'],
['Fiscal policy','Expansionary fiscal policy = ?','Cut taxes and/or increase government spending → larger deficits, higher demand. Contractionary = raise taxes / cut spending.'],
['Economic theory','Keynesian vs. Monetarist vs. Supply-side?','Keynesian: government spending/fiscal policy drives demand. Monetarist (Friedman): money supply is what matters; steady growth of money. Supply-side: cut taxes and regulation to boost production.'],
['Money supply','M1 vs. M2 vs. M3?','M1 = currency + demand deposits (checking) + other checkable deposits. M2 = M1 + savings, money market accounts, small (<$100k) time deposits, retail MMFs. M3 = M2 + large time deposits + institutional MMFs.'],
['Money supply','Money multiplier with 10% reserve requirement?','1 ÷ reserve requirement = 1/0.10 = 10. A $1,000 deposit can expand to $10,000 in the banking system.'],
// --- Yield curve ---
['Yield curve','Normal (positive) yield curve means?','Long-term rates > short-term rates. Typical in a healthy expanding economy.'],
['Yield curve','Inverted yield curve means?','Short-term rates > long-term rates. Historically predicts a recession. Occurs when the Fed tightens aggressively.'],
['Yield curve','Flat yield curve?','Short and long rates roughly equal — often a transition point, economy slowing.'],
['Yield curve','Three theories explaining yield curve shape?','Expectations theory (curve reflects expected future short rates), Liquidity preference (investors demand premium for longer maturities), Market segmentation (separate supply/demand at each maturity).'],
// --- International ---
['International','Balance of payments: current account vs. capital account?','Current account: trade in goods & services, income, transfers (trade deficit lives here). Capital account: investment flows (purchases of assets/securities).'],
['International','If the U.S. dollar STRENGTHENS, effect on U.S. exports and imports?','Exports fall (U.S. goods cost more abroad), imports rise (foreign goods cheaper). Trade deficit widens. Weak dollar → the opposite; helps exporters.'],
['International','What tends to strengthen a currency?','Higher relative interest rates, low inflation, strong economy, political stability, trade surplus.'],
['International','Interest rates rise in the U.S. — effect on dollar?','Dollar strengthens (foreign capital flows in to capture higher yields).'],
['International','Which is a U.S. investor\'s risk when buying a foreign bond and the foreign currency weakens?','Currency (exchange-rate) risk — the investor receives fewer dollars when converting back. A strengthening foreign currency helps the U.S. investor.'],
// --- Financial statements ---
['Financials','Balance sheet equation?','Assets = Liabilities + Shareholders\' Equity (net worth).'],
['Financials','Current ratio formula and meaning?','Current assets ÷ current liabilities. Measures short-term liquidity. Higher = more liquid.'],
['Financials','Quick ratio (acid test)?','(Current assets − inventory) ÷ current liabilities. Stricter liquidity measure.'],
['Financials','Working capital?','Current assets − current liabilities.'],
['Financials','Debt-to-equity ratio?','Long-term debt ÷ shareholders\' equity. Measures leverage/financial risk. Debt-to-total-capital = LTD ÷ (LTD + equity).'],
['Financials','Book value per share?','(Total shareholders\' equity − preferred stock) ÷ common shares outstanding. Also: tangible net worth excludes intangibles like goodwill.'],
['Financials','Earnings per share (EPS)?','(Net income − preferred dividends) ÷ common shares outstanding. Diluted EPS assumes conversion of convertibles/options.'],
['Financials','Price-to-earnings (P/E) ratio?','Market price per share ÷ EPS. High P/E = growth expectations (or overvaluation). Value investors look for low P/E.'],
['Financials','Dividend payout ratio?','Dividends per share ÷ EPS (or total dividends ÷ net income). Retention ratio = 1 − payout.'],
['Financials','Income statement order: what is EBIT, EBITDA?','Revenue − COGS = gross profit − operating expenses = operating income (EBIT). Add back depreciation & amortization = EBITDA. EBIT − interest = pretax income − taxes = net income.'],
['Financials','Cash flow statement: three sections?','Operating activities, investing activities (capex, buying/selling assets), financing activities (issuing debt/stock, paying dividends, buybacks).'],
['Financials','Is depreciation a cash expense?','No. It is a non-cash expense that reduces reported earnings and taxes, but is added back in the cash flow statement.'],
['Financials','FIFO vs. LIFO in inflation?','LIFO: newer, higher costs expensed → lower reported profit and lower taxes (inventory on balance sheet understated). FIFO: higher profit, higher taxes, inventory closer to market value.'],
['Financials','Return on equity (ROE)?','Net income ÷ shareholders\' equity. Measures profitability relative to owners\' capital.'],
['Financials','Footnotes to financial statements contain?','Accounting methods, contingent liabilities, pending litigation, off-balance-sheet items, stock option details. Always read them.'],
// --- Other ---
['Business info','Form 10-K vs. 10-Q vs. 8-K?','10-K: annual audited report. 10-Q: quarterly unaudited report. 8-K: current report of a material event (merger, bankruptcy, change of auditor), generally within 4 business days.'],
['Business info','Who audits public company financials and who regulates the auditors?','Independent CPAs; overseen by the PCAOB, created by Sarbanes-Oxley (2002). SOX also requires CEO/CFO certification of financials.'],
['Business info','Under what regulation must companies disclose material info to all investors at once?','Regulation FD (Fair Disclosure) — no selective disclosure to analysts/institutions.'],
['Time value','Present value vs. future value — which is discounting?','PV discounts future cash flows back to today at a rate. FV compounds. Higher discount rate → lower PV. Rule of 72: years to double = 72 ÷ rate.'],
['Time value','Net present value (NPV) rule?','NPV = PV of inflows − initial cost. Accept if NPV > 0. IRR is the discount rate that makes NPV = 0. For bonds, IRR = yield to maturity.'],
['Time value','What does IRR assume about reinvestment?','That all cash flows are reinvested at the IRR itself. Use IRR to evaluate investments with uneven cash flows (e.g., bonds, real estate).'],
['Statistics','Mean, median, mode?','Mean = average. Median = middle value when sorted (less affected by outliers). Mode = most frequent value.'],
['Statistics','Standard deviation measures what?','Total risk / volatility of returns around the mean. ~68% of returns within 1 SD, ~95% within 2 SD, ~99% within 3 SD (normal distribution).'],
['Statistics','Geometric vs. arithmetic mean return?','Geometric (compound, time-weighted) accounts for compounding and is always ≤ arithmetic. Use geometric for multi-period performance.'],
['Statistics','Correlation coefficient range and meaning?','−1 to +1. +1 moves in lockstep; 0 no relationship; −1 perfectly opposite. Diversification benefit increases as correlation drops below +1.'],
['Statistics','What is beta?','Measure of a security\'s volatility relative to the market (systematic risk). Market = 1.0. Beta 1.5 moves 50% more than the market. Beta < 1 is less volatile.'],
['Statistics','What is alpha?','Return above (or below) what beta/CAPM predicts — the value added by the manager. Positive alpha = outperformed on a risk-adjusted basis.'],
['Statistics','Skewness and kurtosis?','Skew: asymmetry of returns (negative skew = long left tail of big losses). Kurtosis: "fat tails" — more extreme outcomes than a normal curve.'],
['Macro','Unemployment: frictional, structural, cyclical?','Frictional: between jobs (normal). Structural: skills mismatch/industry change. Cyclical: caused by recession. Full employment still has frictional + structural.'],
['Macro','Dow Jones Industrial Average vs. S&P 500 vs. Russell 2000 vs. Wilshire 5000?','DJIA: 30 large stocks, price-weighted. S&P 500: 500 large caps, cap-weighted. Russell 2000: small caps. Wilshire 5000: broadest U.S. index. NASDAQ Composite: tech-heavy.'],
['Macro','What is a "soft landing"?','Fed slows inflation by raising rates WITHOUT triggering a recession.'],
['Macro','Consumer confidence and durable goods orders are which type of indicator?','Leading indicators.'],
['Macro','Capital markets vs. money markets?','Money market: short-term (≤1 year) debt — T-bills, CP, CDs, repos, banker\'s acceptances. Capital market: long-term debt and equity.'],
].forEach(function (c) { window.CARDS.push({ section: 'econ', topic: c[0], q: c[1], a: c[2] }); });
