// Section 3: Client Investment Recommendations and Strategies (39 questions, ~30%)
window.CARDS = window.CARDS || [];
[
// --- Client profile & suitability ---
['Suitability','What must an adviser gather before making a recommendation?','Financial situation (income, net worth, liquidity), objectives, time horizon, risk tolerance, tax status, age, other holdings, liquidity needs, experience. Non-financial: family, health, values. Objectives + time horizon + risk tolerance are the core.'],
['Suitability','Investment objectives ranked from safest to most aggressive?','Preservation of capital → income → growth & income → growth → aggressive growth/speculation.'],
['Suitability','Client needs money in 2 years for a house down payment — recommend?','Money market fund, T-bills, short-term CDs/bonds. Never equities for a short horizon; capital preservation and liquidity dominate.'],
['Suitability','Retired client needs income, moderate risk?','High-quality bonds, preferred stock, dividend-paying blue chips, bond ladders, balanced/income funds. Some equity to fight inflation over a long retirement.'],
['Suitability','Young client, long horizon, high risk tolerance?','Growth stocks/equity funds, small cap, international. Time horizon allows riding out volatility.'],
['Suitability','Client in high tax bracket wants income in a taxable account?','Municipal bonds (compare tax-equivalent yield). Never munis inside an IRA/401(k).'],
['Suitability','Investment policy statement (IPS) contains?','Objectives, constraints (time, liquidity, taxes, legal, unique circumstances), asset allocation targets, rebalancing rules, benchmarks, responsibilities. Does NOT list specific securities.'],
['Suitability','Capital needs analysis?','Determine future amount needed (adjusted for inflation), subtract expected resources, compute required savings/return. Use PV/FV math.'],
// --- Risk types ---
['Risk','Systematic vs. unsystematic risk?','Systematic (market): affects the whole market — cannot be diversified away (market, interest rate, inflation, currency, political). Unsystematic: specific to a company/industry — diversified away (business, financial, regulatory, liquidity).'],
['Risk','Beta measures which risk?','Systematic (market) risk.'],
['Risk','Standard deviation measures which risk?','Total risk (systematic + unsystematic).'],
['Risk','Interest rate risk vs. reinvestment risk — which bond has NO reinvestment risk?','Zero-coupon bond has no reinvestment risk (no coupons) but the highest interest-rate risk for its maturity.'],
['Risk','Liquidity risk vs. marketability?','Liquidity: ability to sell quickly at fair value. Illiquid: DPPs, non-traded REITs, hedge funds, real estate, thinly traded stocks, annuities (surrender charges).'],
['Risk','Purchasing power (inflation) risk hurts which investments most?','Fixed-income and cash. Long-term bonds, fixed annuities. Hedge with equities, real assets, TIPS.'],
['Risk','Regulatory / legislative risk?','Law or rule changes affect an investment (e.g., tax law removing muni exemption, tariffs).'],
['Risk','Opportunity cost?','Return given up by choosing one investment over another (e.g., keeping cash vs. investing).'],
// --- Portfolio theory ---
['MPT','Modern Portfolio Theory (Markowitz) core idea?','Evaluate securities by their effect on portfolio risk/return, not in isolation. Combine assets with low correlation to reduce risk for a given return. Efficient frontier = best return per unit of risk.'],
['MPT','Efficient frontier?','Set of portfolios offering the highest expected return for each level of risk. Portfolios below the frontier are inefficient. Investors pick the point matching their risk tolerance.'],
['MPT','CAPM formula?','Expected return = Rf + β(Rm − Rf). Rf = risk-free rate (T-bill). (Rm − Rf) = market risk premium. Only systematic risk is rewarded.'],
['MPT','Stock beta 1.2, risk-free 3%, market return 8%. Expected return?','3 + 1.2(8 − 3) = 3 + 6 = 9%.'],
['MPT','Sharpe ratio?','(Portfolio return − Rf) ÷ standard deviation. Excess return per unit of TOTAL risk. Higher is better. Best for comparing overall portfolios.'],
['MPT','Treynor vs. Jensen\'s alpha?','Treynor = (Rp − Rf) ÷ beta — excess return per unit of SYSTEMATIC risk. Jensen\'s alpha = actual return − CAPM expected return.'],
['MPT','Efficient Market Hypothesis: weak, semi-strong, strong?','Weak: prices reflect past prices → technical analysis useless. Semi-strong: prices reflect all public info → fundamental analysis useless. Strong: prices reflect all info including inside info → nothing works. EMH implies passive/index investing.'],
['MPT','Capital Market Line vs. Security Market Line?','CML: risk (std dev) vs. return for efficient PORTFOLIOS. SML: beta vs. return for individual SECURITIES (graph of CAPM).'],
['MPT','Monte Carlo simulation?','Runs thousands of random return scenarios to estimate probability of meeting a goal (e.g., not running out of money in retirement). Output is a probability, not a guarantee.'],
['Behavioral','Behavioral finance biases: name and define 5','Overconfidence, anchoring (fixating on a reference price), herding, loss aversion (losses hurt more than gains please), confirmation bias, recency bias, mental accounting, regret aversion, framing.'],
// --- Strategies ---
['Strategy','Strategic vs. tactical asset allocation?','Strategic: long-term target mix based on goals/risk (passive), rebalanced periodically. Tactical: short-term shifts to exploit market conditions (active, market timing).'],
['Strategy','Rebalancing — why and how?','Restore target allocation after drift; forces "sell high, buy low." Calendar-based or threshold-based. Consider tax consequences in taxable accounts.'],
['Strategy','Active vs. passive management?','Active: try to beat the benchmark via selection/timing; higher fees, tax drag. Passive: index/buy-and-hold; lower cost, supported by EMH.'],
['Strategy','Dollar cost averaging?','Invest fixed $ at regular intervals; buy more shares when prices low, fewer when high. Average cost per share < average price per share. Doesn\'t guarantee profit or protect in a declining market.'],
['Strategy','Growth vs. value investing?','Growth: high P/E, high earnings growth, low/no dividends, momentum. Value: low P/E, low price-to-book, high dividend yield, "undervalued." Contrarian: buy what is out of favor.'],
['Strategy','Top-down vs. bottom-up analysis?','Top-down: economy → sector → company. Bottom-up: start with individual company fundamentals regardless of macro.'],
['Strategy','Bond ladder vs. barbell vs. bullet?','Ladder: staggered maturities, reduces reinvestment & rate risk. Barbell: short + long only. Bullet: all maturing around one date (for a known liability).'],
['Strategy','Fundamental vs. technical analysis?','Fundamental: financial statements, earnings, management, economy — determines what to buy. Technical: charts, volume, trends, support/resistance, moving averages — determines when.'],
['Strategy','Technical terms: support, resistance, head and shoulders, breakout?','Support: price floor where buying appears. Resistance: ceiling. Head & shoulders top: bearish reversal (inverted = bullish). Breakout: price moves through support/resistance on volume.'],
['Strategy','Buy-and-hold advantages?','Low transaction costs, tax deferral of gains (long-term rates), no market timing needed. Disadvantage: portfolio drifts from target.'],
['Strategy','Index/core-satellite approach?','Core in low-cost index funds, satellites in active/alternative positions for potential alpha.'],
['Strategy','Sector rotation?','Shifting among industry sectors based on business cycle stage (e.g., cyclicals early expansion, defensives late/contraction).'],
['Strategy','Hedging with options: long stock — hedge with?','Buy a put (protective put). Short stock — hedge by buying a call.'],
// --- Performance measurement ---
['Performance','Total return formula?','(Ending value − beginning value + income) ÷ beginning value. Includes dividends/interest AND price change.'],
['Performance','Holding period return vs. annualized return?','HPR is total return over the holding period regardless of length. Annualize to compare investments held for different periods.'],
['Performance','Time-weighted vs. dollar-weighted return?','Time-weighted: measures the MANAGER (ignores timing of cash flows) — required by GIPS for mutual funds. Dollar-weighted (IRR): measures the INVESTOR\'s actual experience, affected by when money was added/withdrawn.'],
['Performance','Real return?','Nominal return − inflation. 8% return with 3% inflation ≈ 5% real.'],
['Performance','After-tax return?','Return × (1 − tax rate). 6% taxable at 24% = 4.56% after tax.'],
['Performance','Inflation-adjusted after-tax return: 7% return, 3% inflation, 25% tax?','After-tax: 7 × 0.75 = 5.25%. Then subtract inflation: 5.25 − 3 = 2.25%.'],
['Performance','Benchmark selection?','Compare a portfolio to an index with similar style/asset class (small cap fund → Russell 2000, not S&P 500). Bonds → Bloomberg U.S. Aggregate.'],
['Performance','Expected return calculation?','Sum of (probability × return) for each scenario. E.g., 50% chance of 10%, 50% chance of −2% → 4%.'],
['Performance','Rule of 72?','Years to double = 72 ÷ annual rate. At 8%: 9 years. At 6%: 12 years.'],
['Performance','Yield to maturity vs. current yield — which considers the discount/premium?','YTM includes coupon income plus the gain (discount) or loss (premium) to maturity. Current yield only looks at coupon ÷ price.'],
// --- Taxes ---
['Taxes','Long-term vs. short-term capital gains?','Held > 1 year = long-term (0/15/20% rates). ≤ 1 year = short-term, taxed as ordinary income. Holding period starts the day AFTER trade date.'],
['Taxes','Capital loss deduction rules?','Losses offset gains (short vs. short, long vs. long, then net). Up to $3,000 of net loss deductible against ordinary income per year; excess carried forward indefinitely.'],
['Taxes','Wash sale rule?','Loss disallowed if substantially identical security is bought within 30 days BEFORE or AFTER the sale (61-day window). Disallowed loss is added to the cost basis of the new shares. Applies to calls/convertibles too.'],
['Taxes','Qualified dividends taxed at?','Long-term capital gains rates (0/15/20%). Must hold stock > 60 days around the ex-date. REIT dividends and money market dividends are NOT qualified (ordinary rates).'],
['Taxes','Cost basis methods for selling shares?','FIFO (default), specific identification (most tax control), average cost (mutual funds only). Choose specific ID to sell high-basis lots to minimize gains.'],
['Taxes','Cost basis of inherited securities vs. gifted securities?','Inherited: stepped up (or down) to FMV at date of death; always long-term. Gifted: donor\'s basis carries over (if FMV > basis); if FMV < basis at gift, use FMV for losses (double basis rule).'],
['Taxes','Gift tax annual exclusion and who pays?','$19,000 per recipient per year (2025), unlimited to a spouse (U.S. citizen). Donor pays any gift tax. Gifts above exclusion use the lifetime unified credit.'],
['Taxes','Estate tax — what\'s included and marital deduction?','Gross estate: all property owned at death incl. life insurance owned by decedent, half of jointly held with spouse. Unlimited marital deduction to a U.S. citizen spouse. Estate tax return due 9 months after death; alternate valuation date 6 months after death.'],
['Taxes','Progressive vs. regressive tax?','Progressive: rate rises with income (income tax, estate tax). Regressive: same rate regardless (sales tax, excise, payroll/FICA up to cap) — takes larger % from low earners.'],
['Taxes','Alternative minimum tax (AMT) — what triggers it?','Tax preference items: private-activity muni bond interest, ISO bargain element, accelerated depreciation, certain deductions. Investors in high brackets should avoid private-activity munis if subject to AMT.'],
['Taxes','Tax treatment: annuity vs. life insurance death benefit?','Annuity: earnings taxed to beneficiary as ordinary income (no step-up). Life insurance death benefit: income-tax free to beneficiary (but in the estate if the decedent owned the policy).'],
['Taxes','Roth conversion — taxable?','Yes, converted amount taxed as ordinary income in the year of conversion; no 10% penalty. Good when in a low bracket now, expecting a higher one later.'],
['Taxes','Required minimum distributions — age and penalty?','Begin by April 1 of the year after turning 73 (SECURE 2.0). Penalty for missing = 25% (10% if corrected timely). Roth IRAs have no RMDs for the original owner.'],
['Taxes','Early withdrawal penalty exceptions for IRAs?','Death, disability, first home ($10k), qualified education, medical > 7.5% AGI, health insurance if unemployed, substantially equal periodic payments (72(t)), birth/adoption ($5k). Still taxed as ordinary income.'],
['Taxes','Net investment income tax?','Additional 3.8% on investment income for high earners (MAGI > $200k single / $250k joint).'],
['Taxes','Tax-loss harvesting?','Sell losers to realize losses that offset gains; replace with a similar (not substantially identical) security to keep market exposure and avoid the wash sale rule.'],
['Taxes','Which account type for a client who expects to be in a HIGHER bracket at retirement?','Roth (pay tax now at low rate, withdraw tax-free later). Lower bracket later → traditional (deduct now).'],
// --- Account types & estate ---
['Accounts','Joint tenants with right of survivorship (JTWROS) vs. tenants in common (TIC)?','JTWROS: equal ownership, passes to survivor outside probate (spouses). TIC: unequal ownership allowed; deceased\'s share goes to their estate/heirs.'],
['Accounts','Transfer on death (TOD) account?','Individual account that passes to named beneficiary at death, avoiding probate. Owner keeps full control during life.'],
['Accounts','Revocable vs. irrevocable trust?','Revocable (living): grantor keeps control, can change it, assets IN grantor\'s estate, avoids probate but no tax benefit. Irrevocable: grantor gives up control; assets OUT of estate; can save estate tax.'],
['Accounts','Trust parties: grantor, trustee, beneficiary; who is the fiduciary?','Grantor/settlor creates and funds the trust. Trustee holds legal title and manages under the Prudent Investor Rule (fiduciary). Beneficiary holds equitable title.'],
['Accounts','Simple vs. complex trust taxation?','Simple: must distribute all income annually; beneficiary pays tax. Complex: may accumulate income; trust pays tax at compressed brackets (hits top rate quickly). Trusts file Form 1041.'],
['Accounts','Durable power of attorney?','Authorization to act on someone\'s behalf that SURVIVES the principal\'s incapacity (regular POA does not). All POAs terminate at death.'],
['Accounts','Discretionary account requirements?','Written authorization from client BEFORE any discretion is exercised. Under USA, an IA may exercise oral discretion for 10 business days pending written authorization. Discretion = choosing the security, amount, or action (not just time/price).'],
['Accounts','Margin account basics: Reg T, who sets it?','Federal Reserve Board sets Reg T = 50% initial deposit for equities. Broker-dealer sets house maintenance (FINRA minimum 25%). Margin magnifies gains AND losses; interest charged on debit balance.'],
['Accounts','Custodial account (UTMA) — who is taxed, who controls?','Minor is the owner (minor\'s SSN, kiddie tax rules); one custodian manages as fiduciary; gifts are irrevocable; no margin, no options writing; minor takes control at age of majority.'],
['Accounts','ERISA Section 404(c) safe harbor?','Employer relieved of liability for participant investment choices if plan offers ≥3 diversified options, allows changes at least quarterly, and provides sufficient information/education.'],
['Accounts','Prudent Investor Rule (UPIA) key points?','Judge the PORTFOLIO as a whole, not each investment; diversification required; consider risk/return, inflation, costs; can delegate investment management; no investment is per se imprudent.'],
['Accounts','Bypass (credit shelter) trust purpose?','Uses the first spouse\'s estate tax exemption so it isn\'t wasted; assets skip the surviving spouse\'s estate.'],
['Accounts','Individual account — who can enter orders?','Only the account owner, or someone with written trading authorization (POA). A spouse cannot trade without it.'],
].forEach(function (c) { window.CARDS.push({ section: 'rec', topic: c[0], q: c[1], a: c[2] }); });
